export const UPDATE_NEWS_LIST ="UPDATE_NEWS_LIST";
export const UPDATE_TOTAL_COUNT = "UPDATE_TOTAL_COUNT";
export const UPDATE_PAGE_NUMBER = "UPDATE_PAGE_NUMBER";
export const UPDATE_SELECTED_NEWS = "UPDATE_SELECTED_NEWS";